### ISSUE TITLE
Performance issues with GFLiveScannerViewController

### ISSUE THREAD

**Issue by AnthoPakPak** [gualtierofrigerio/GFLiveScanner#2]
Hey, thanks for the library!

I've successfully integrated `GFLiveScannerViewController` into my project. Unfortunately, I've then discovered that my UI was getting slow and unresponsive after a few seconds.
After trying again the Demo app, I've made the same observations.

To reproduce:
- Open Demo app
- Click OCR VC
- Target some text with camera (it seems like more text causes more unresponsiveness)
- After a few seconds, you will notice it's harder to pull down the view controller to dismiss
- If you keep scanning text, it becomes less and less responsive

Have you faced this issue too? I've checked the code but can't find where I could patch the issue. I bet it's a matter of moving the text recognition from main thread to a background thread.

Any help is appreciated 🤗

**Comment by gualtierofrigerio** [comment]
Thanks for your comment and your interest in the library :) 

I didn't use the OCR much at the time I shared this (more the barcode), at least not in live mode so I don't remember if I had performance issues. Having a quick look at the code now I think a possibility could also be avoiding queueing too many requests in GFOcrHelper, I don't remember exactly the logic but I think I implemented a list of requests to process them one at a time. Maybe too many requests are made and this is a problem so a threshold could be set, like no more than X requests process per second and you drop the others. 
I don't know when I'll have time to test this approach but it may be a possibility to explore.

**Comment by AnthoPakPak** [comment]
Hey, thanks a lot for your quick answer!

Thanks to your insights, I've took another look and managed to improve performances by:
- Moving VNRecognizeTextRequest to a background thread (this is the main thing, allowing to not block the UI)
- Removing the queuing of requests, I don't need it in my use case

It's now behaving well enough for my use. Thanks for your work on this!

**Comment by gualtierofrigerio** [comment]
thanks for the feedback, maybe I could change something in order to have the queue or requests as an option instead of being the default and of course a different thread for some of the operations, I thought it was already like that but it wasn't...
